name: ?? Deploy website on push to master

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: ğŸ‰ Deploy website on push to master
    runs-on: ubuntu-latest
    steps:
      - name: ğŸššGet latest code
        uses: actions/checkout@v4

      - name: ğŸ“Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./sherpath-theme/
          server-dir: /sherpath.jp/wp-content/themes/sherpath-theme/